% -------------------------------------------------------------------
%  Generated by MATLAB on 1-Nov-2015 13:48:56
%  MATLAB version: 8.6.0.267246 (R2015b)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

hmm1 = saveVarsMat.hmm1; % <1x14 HMM> unsupported class

clear saveVarsMat;
